### ISSUE TITLE
Natural gas unit conversion not working

### ISSUE THREAD

**Issue by rosewangrmi** [RMI/OPEM#4]
@zacharyschmidt 
Hi Zach, I think 1 BOE= 6 MCF conversion is not working in this code. Can you please help fix it?
https://github.com/RMI/OPEM/blob/9c266d9a7f2a2f008ec004f9c944bd6ffa2158de/src/opem/combustion/combustion_EF.py#L123

**Comment by zacharyschmidt** [comment]
Hi Rose,

The root issue is that the natural gas calculations were using gas volume expressed in BOED, but the calculations were written for units of MCFD. Please take a look at the fix and see if the output is correct now.

**Comment by rosewangrmi** [comment]
> 

Thanks Zach. I'm closing this issue now.
